apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eke0gszol-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eke0gszol-python 
  name: eke0gszol-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: eke0gszol-python 
